services:
  trading_bot:
    build: .
    container_name: trading_bot
    volumes:
      - ./:/app
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser"]
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/trading_bot_db
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trading_bot_db
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
